export enum TematicaEnum {
    AVENTURAS="AVENTURAS",
    BELICO="BELICO",
    DEPORTIVO="DEPORTIVO",
    FANTASTICO="FANTASTICO",
    CIENCIA_FICCION="CIENCIA_FICCION",
    HISTORICO="HISTORICO",
    HORROR="HORROR"
    ,
}
